import requests
import re
from urllib.parse import urlparse, parse_qs

def test_callback(full_url, product_name):
    """Test a callback URL"""
    
    parsed = urlparse(full_url)
    base_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
    query_params = parse_qs(parsed.query)
    params = {k: v[0] for k, v in query_params.items()}
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
        'Accept': '*/*',
        'Accept-Language': 'en-US,en;q=0.9',
        'Referer': 'https://www.google.com/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
    }
    
    print("\n" + "="*80)
    print(f"TESTING: {product_name.upper()}")
    print("="*80)
    
    response = requests.get(base_url, params=params, headers=headers, timeout=15)
    
    print(f"Status: {response.status_code}, Size: {len(response.text):,} bytes")
    
    if len(response.text) > 500:
        prices = re.findall(r'\$([0-9]+\.[0-9]{2})', response.text)
        print(f"✅ SUCCESS! {len(prices)} prices")
        print(f"Sample: {prices[:5]}")
        
        keyword_count = response.text.lower().count(product_name.lower())
        print(f"{product_name} mentions: {keyword_count}")
        return True
    else:
        print(f"❌ Failed: {response.text}")
        return False

if __name__ == "__main__":
    # All your callbacks from the messages
    callbacks = [
        ("https://www.google.com/async/callback:6948?fc=EswCCowCQUxrdF92RkdiNWlYZVhZVEMyak1wZUtMUi1vdVNUQmFBRk9VeERPOTd6S2V1MVdTZEMzVG9jc1l3UUEyYzZicWh4YVVXZ2NkY2JHQUdDVXZKRWNzOGNMSkdXREFyVm5Cek9zS3dDTlRfaU41MEh0Y1hWaG05Z0RvaTR1akk3YTQ1b2ZZRXRDM3duSjhRMmxuYm1ORzhidW9OaEwzTGVqbEN0TjZuQWFuWnZqT0kxX2t2a1puRkNJNGdYM0xMRTdhTnNLTWY1V0k3OFZUeFdkaWpsWlN4M2hEOVlsakR5NFZsRXhrUmFoSzloa3E1V1FWWXpTUzFtVHlkUXVuUUwycUFUNHFjUXd3b3BIcBIXd0ZzZWFkcllHZlhGcDg0UHktV0tnUVUaIkFGTUFHR3JnRkszc1YwcnZvZnR1bFNGU1lZUVl6MmJJNlE&fcv=3&vet=12ahUKEwjauJPct_-QAxX14skDHcuyIlAQ9pcOegQIBhAB..i&ei=wFseadrYGfXFp84Py-WKgQU&opi=95576897&sca_esv=3a898889caaec7e6&shopmd=1&udm=28&yv=3&cs=0&async=_basejs:%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en.62X82fu0cRg.2019.O%2Fam%3DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAEACAgAAAQIEAAAIAAAAAAAAAAAIQABAAAAAAAAAAAAAAAAAAAAAAAABAAAEACAAgAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAADIAAAEAAAQUAAAAKAAAAAAAAAAAAAAAAgAAIAAAAAAASIAHAf_sDDgAAAAAAAAAIAAAAAAAAAAAAAAAAIgAAAAAAAABgAQCAoDAAAAEIAQQAAAAAAAAAAAAAAAAAEAAAAAAAAAABAAAAACAAAAAABQAABAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAIAAAAHAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAIaAAAAAAAAEABAAAAAABAAAAAAAAOAAAgBAAAALCAIgEAQAAAAABADgCPB3BIQQEAAAAAAAAAAAAAAAAAAAAAAqAgmAPpBwQQAAAAAAAAAAAAAAAAAAAAAAAAgBRhE2sNAAg%2Fdg%3D0%2Fbr%3D1%2Frs%3DACT90oGEcnIayEDH1eOwi1CEcyYaaiaGTg,_basecss:%2Fxjs%2F_%2Fss%2Fk%3Dxjs.s.aBXVAzA1pXU.L.B1.O%2Fam%3DAAAEAAAgEAAAAAAAAAAAAAAIAIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAQAAAAlCGAAAAAAAAQC8AAJACAAAAAAAAAA8AABAEAAAAAAAAAAACAAAgAQAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAIABAEAAIQAAAAAABQAgAAAAAAAAAAAAAAAIAAAAAAAAAAEAAAAADBgAAEAAAAAAQCAAABAAAAAQAAAGAGEAAAAAADIAAAAAAAAAAAEAAQAAAAAAAIgACCAAQAAAAAAAYAAAAAAAAIABsCAgCIBAhQgAABwAAAAAAAAACAAAAAAAAABQACACAjkAAAAAAAEAABAAAPIAAAAgAAAIQEAA4A0QGAAAAAIBACIAAAAAQAJAIAgAAEBBAAgAAAAAAAAAAABGAAAAAACwALCIIgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAABA%2Fbr%3D1%2Frs%3DACT90oF9ANDsgGHI0gEN2wj-txOHBTFNVg,_basecomb:%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en.62X82fu0cRg.2019.O%2Fck%3Dxjs.s.aBXVAzA1pXU.L.B1.O%2Fam%3DAAAEAAAgEAAAAAAAAAAAAAAIAIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAEAAAAAAAAAAgAEACAgAAAQIEAAlKGAAAAAAAAQC8QAJACAAAAAAAAAA8AABAEAAAAAABAAAECCAAgAQAAAAAAAAAAAAAAAAAAQAAAACAAAAAADIABAEAAIQUAAAAKBQAgAAAAAAAAAAAAgAAIAAAAAAASIAHAf_sDDhgAAEAAAAAIQCAAABAAAAAQAAAGImEAAAAAADJgAQCAoDAAAAEIAQQAAAAAAIgACCAAQAAAEAAAYAAAAAABAIABsCAgCIBAhQgABBwAAAAAAAAACAAAAAAAAEBQACACAjkAAAAAAAEAIBAAAPIAAAAggAAIQEAA4A0QGAAAAAIBACIAAAAIaAJAIAgAAEBBAAgAAABAAAAAAABOAAAgBACwALCIIgEAQAAAAABADgCPB3BIQQEAAAAAAAAAAAAAAAAAAAAAAqAgmAPpFwQQAAAAAAAAAAAAAAAAAAAAAAAAgBRhE2sNAAg%2Fd%3D1%2Fed%3D1%2Fdg%3D0%2Fbr%3D1%2Fujg%3D1%2Frs%3DACT90oH3y-rcxRINDFaPYcqCYahZDf8bVA,_fmt:prog,_id:fc_wFseadrYGfXFp84Py-WKgQU_1", "milk"),
        
        ("https://www.google.com/async/callback:6948?fc=EvcBCrcBQUxrdF92SDdmVHBZcHBnNGNYY1F6bkJGMzgzWVdOeEplam1fQTdzVG12RUJ0ZWRYWXJVX1pVcDhRSHRoYVhGenVDaGszN3R2WWcxTWI1Q2ZyVEZXanRfRXJOLTU0UG03WlhwbWwwTWtXZy1KQ25OVlRUVjBEd21XTEhIMEFZR3NEMVpJNWhPNDNqWlBnZUpxUE13ZGg4R2ZHRVRYc2g0Q2doNVlBcll1NnBKdzB2YmM4RGFURFk4EhdEbFllYWNTZEFZS0l3YmtQa3EyWXVRdxoiQUZNQUdHcmNOQTRWYkpmNFA1cFQ3VEhfd1VtSGs0NVh2dw&fcv=3&vet=12ahUKEwjE3N2ksv-QAxUCRDABHZIWJscQ9pcOegQICBAB..i&ei=DlYeacSdAYKIwbkPkq2YuQw&opi=95576897&udm=28&yv=3&cs=0&async=_basejs:%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en.2vGmv4GXqLc.2019.O%2Fam%3DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAgIAAAUCAAgAAAAAAAAAAAgAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAQQAAAAgBIAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAABkAAACCAgAIAAAAKAAAAAAAAAAAAAAAAgAAIAAAAAAAkQAKA__YHHAAAAAAAAAACAAAAAAAAAAAAAAAAIgAAAAAAAABgAQBAUBgAgACEAAIAAAAAAAAAAAAAAAAAIAAAAAAAAAACAAAAAEAAAAAACgAACAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAIAAAAHAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABDQAAAAAAABAAQAAAAAAQAAAAAAADgAAIAQAAABwAUUCAIAAAAAAgBwAHg_gkIICAAAAAAAAAAAAAAAAAAAAAARAQTAHkh8QQAAAAAAAAAAAAAAAAAAAAAAAAABShE2sNQAg%2Fdg%3D0%2Fbr%3D1%2Frs%3DACT90oEnKtygzCvFbE-Yq3qhFx23ZDTJpw,_basecss:%2Fxjs%2F_%2Fss%2Fk%3Dxjs.s.O3GRMCji4N4.L.B1.O%2Fam%3DAAAEAAAQCAAAAAAAAAAAAAACACAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAEACAAJQhAAAAAAAA0AsAAKQAAAAAAAAAwAMAAAQBAAAAAAAAAIAAAABIAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAMAAACCAEAAAAAAABQAgAAAAAAAAAAAAAAAIAAAAAAAAAAIAAAAAGDAAABAAAAAAEAgAAAgAAAAQAAAGAGEAAAAAADIAAAAAAAAAgACAAAAAAAAAABABEEAAgAAAAAAAwAAAAAAAAAADYEFAEACBChEAADgAAAAAAAAAEAAAAAAAAABAAYAICOQAAAAAABAAAAABACAPAAAAAgCAAAQEAHgDCAwAAACBAAARAAAAACABIBAEAABAQQAIAAAAAAAAAAAARgAAAAAALAAWUSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAABA%2Fbr%3D1%2Frs%3DACT90oEJ6p-PTgBZVFLgOaKVP94f0tpUyg,_basecomb:%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en.2vGmv4GXqLc.2019.O%2Fck%3Dxjs.s.O3GRMCji4N4.L.B1.O%2Fam%3DAAAEAAAQCAAAAAAAAAAAAAACACAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAIABAAgIAAAUCCAgJQhAAAAAAAA0AsEAKQAAAAAAAAAwAMAAAQBAAAAAAAQQIAAAgBIAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAABsAAACCAkAIAAAAKBQAgAAAAAAAAAAAAgAAIAAAAAAAkQAKA__YHHDAAABAAAAACEAgAAAgAAAAQAAAGImEAAAAAADJgAQBAUBgAgACEAAIAAAAAABABEEAAgAAAIAAAwAAAAAACAAADYEFAEACBChEACDgAAAAAAAAAEAAAAAAAAABBAYAICOQAAAAAABAAAAIBACAPAAAAAgiAAAQEAHgDCAwAAACBAAARAAAABDQBIBAEAABAQQAIAAAAQAAAAAAATgAAIAQAsABwEUUCAIAAAAAAgBwAHg_gkIICAAAAAAAAAAAAAAAAAAAAAARAQTAHkl8QQAAAAAAAAAAAAAAAAAAAAAAAAABShE2sNQAg%2Fd%3D1%2Fed%3D1%2Fdg%3D0%2Fbr%3D1%2Fujg%3D1%2Frs%3DACT90oEp5QFDlLHErlYA1d3BMRU43THuCQ,_fmt:prog,_id:fc_DlYeacSdAYKIwbkPkq2YuQw_1", "bread"),
        
        ("https://www.google.com/async/callback:6948?fc=EvcBCrcBQUxrdF92SFJkeTlPRnRLZHRXMVRhRXdTLVJnQnFjODNPaXJSVGZNcWxCYWJYQ3FqaE5yRjNYaFlweFEyLWdKdjZMV2F1MThiczA5NF9RTjdvQVh3NDlYZlJoVDBJSnZGSGwyN2xzNUU3N0JSN0RsYlE1VlhZU2lpVlp0VlFqLVBYVlBUM05sajRrYXMzUnlRM3RqT0tFMzdXdFhveFVnVG5IdjNkZXcxa3RpdWZNSGI0NXdYblV3EhdEMUllYWZPUUJNSEFwODRQclptSGlRYxoiQUZNQUdHcHNIRGo5QlBXMlBNZUd4Q191ZlFacG9ldGExUQ&fcv=3&vet=12ahUKEwiz1Pm8rv-QAxVB4MkDHa3MIXEQ9pcOegQIChAB..i&ei=D1IeafOQBMHAp84PrZmHiQc&opi=95576897&udm=28&yv=3&cs=0&async=_basejs:%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en.62X82fu0cRg.2019.O%2Fam%3DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAEACAgAAAQIEAAAIAAAAAAAAAAAIQABAAAAAAAAAAAAAAAAAAAAAAAABAAAEACAAgAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAADIAAAEAAAQUAAAAKAAAAAAAAAAAAAAAAgAAIAAAAAAASIAHAf_sDDgAAAAAAAAAIAAAAAAAAAAAAAAAAIgAAAAAAAABgAQCAoDAAAAEIAQQAAAAAAAAAAAAAAAAAEAAAAAAAAAABAAAAACAAAAAABQAABAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAIAAAAHAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAIaAAAAAAAAEABAAAAAABAAAAAAAAOAAAgBAAAALCAIgEAQAAAAABADgCPB3BIQQEAAAAAAAAAAAAAAAAAAAAAAqAgmAPpBwQQAAAAAAAAAAAAAAAAAAAAAAAAgBRhE2sNAAg%2Fdg%3D0%2Fbr%3D1%2Frs%3DACT90oGEcnIayEDH1eOwi1CEcyYaaiaGTg,_basecss:%2Fxjs%2F_%2Fss%2Fk%3Dxjs.s.aBXVAzA1pXU.L.B1.O%2Fam%3DAAAEAAAgEAAAAAAAAAAAAAAIAIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAQAAAAlCGAAAAAAAAQC8AAJACAAAAAAAAAA8AABAEAAAAAAAAAAACAAAgAQAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAIABAEAAIQAAAAAABQAgAAAAAAAAAAAAAAAIAAAAAAAAAAEAAAAADBgAAEAAAAAAQCAAABAAAAAQAAAGAGEAAAAAADIAAAAAAAAAAAEAAQAAAAAAAIgACCAAQAAAAAAAYAAAAAAAAIABsCAgCIBAhQgAABwAAAAAAAAACAAAAAAAAABQACACAjkAAAAAAAEAABAAAPIAAAAgAAAIQEAA4A0QGAAAAAIBACIAAAAAQAJAIAgAAEBBAAgAAAAAAAAAAABGAAAAAACwALCIIgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAABA%2Fbr%3D1%2Frs%3DACT90oF9ANDsgGHI0gEN2wj-txOHBTFNVg,_basecomb:%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en.62X82fu0cRg.2019.O%2Fck%3Dxjs.s.aBXVAzA1pXU.L.B1.O%2Fam%3DAAAEAAAgEAAAAAAAAAAAAAAIAIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAEAAAAAAAAAAgAEACAgAAAQIEAAlKGAAAAAAAAQC8QAJACAAAAAAAAAA8AABAEAAAAAABAAAECCAAgAQAAAAAAAAAAAAAAAAAAQAAAACAAAAAADIABAEAAIQUAAAAKBQAgAAAAAAAAAAAAgAAIAAAAAAASIAHAf_sDDhgAAEAAAAAIQCAAABAAAAAQAAAGImEAAAAAADJgAQCAoDAAAAEIAQQAAAAAAIgACCAAQAAAEAAAYAAAAAABAIABsCAgCIBAhQgABBwAAAAAAAAACAAAAAAAAEBQACACAjkAAAAAAAEAIBAAAPIAAAAggAAIQEAA4A0QGAAAAAIBACIAAAAIaAJAIAgAAEBBAAgAAABAAAAAAABOAAAgBACwALCIIgEAQAAAAABADgCPB3BIQQEAAAAAAAAAAAAAAAAAAAAAAqAgmAPpFwQQAAAAAAAAAAAAAAAAAAAAAAAAgBRhE2sNAAg%2Fd%3D1%2Fed%3D1%2Fdg%3D0%2Fbr%3D1%2Fujg%3D1%2Frs%3DACT90oH3y-rcxRINDFaPYcqCYahZDf8bVA,_fmt:prog,_id:fc_D1IeafOQBMHAp84PrZmHiQc_1", "chicken"),
        
        ("https://www.google.com/async/callback:6948?fc=EqICCuIBQUxrdF92RlBUeHl5V1ZyV3hrM1ZQd3ZqM01RaEVhY0k2aXRNMEJMUC11ZjlYRTNwQlRkeHpxYkF0emhrS083SEpla2ozdnZzVmdNX1lsenA4SmZYa21KeHNSZk5yWTVnSjFrRngtaHdLOEx0TXJqQUZ1dVFnaUg0Q0tIRGw0WlY5Z0ZoR1RvYkh3QnZkVXZ4S3ZsQThXVFkzbmUtRzZPTjd6S1Z0Y0xpNG5LWndrNXpZMEtfQkNSVTFxOTd5MGpKVV80Y1lOU2oyRXo0NEVaX3M4WWw3UXI1dXVVcmd6ZzI2ZxIXQ2x3ZWFiLV9JWkdQd2JrUHA4NmNvUW8aIkFGTUFHR3FCS2pyQ0cwTkx4WmRQRWI4ajl3cWQ0YkxEcmc&fcv=3&vet=12ahUKEwi_7L__t_-QAxWRRzABHScnJ6QQ9pcOegQIChAB..i&ei=Clweab-_IZGPwbkPp86coQo&opi=95576897&sca_esv=3a898889caaec7e6&shopmd=1&udm=28&yv=3&cs=0&async=_fmt:prog,_id:fc_Clweab-_IZGPwbkPp86coQo_1", "shampoo"),
    ]
    
    print("\n" + "="*80)
    print("TESTING ALL CALLBACKS")
    print("="*80)
    
    results = {}
    for url, product in callbacks:
        results[product] = test_callback(url, product)
    
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    for product, success in results.items():
        status = "✅ WORKS" if success else "❌ FAILED"
        print(f"{product.upper()}: {status}")

